services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5422:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: